config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }

  devise_scope :user do
    delete "/users/sign_out" => "devise/sessions#destroy"
  end

  root "events#index"

  resources :conferences, only: [:index, :edit, :update]

  resources :events do
    member do
      post :list
    end

    resources :comments, only: [:create]
  end

  resources :users, only: [:index] do
    collection do
      get :me
      put :me, action: :update_me
    end

    member do
      post "promote/:role", action: :promote, as: :promote
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :creator, foreign_key: "creator_user_id", class_name: "User"
  belongs_to :event, counter_cache: true

  class << self
    def for_display
      reverse_chronological.includes(:creator)
    end

    def reverse_chronological
      order "created_at DESC"
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    event = Event.find params[:event_id]
    active_user.comment_on_event! params
    flash[:info] = "Thank you for your comment!"
    redirect_to event
  end
end

app/views/comments/_collection.html.erb
<div class="row">
  <div class="col-sm-8">
    <div class="well">
      <h3>Comments</h3>

      <hr />

      <% if active_user.anonymous? %>
        <p>
          Please <a href="<%= user_signup_and_login_path %>">sign in or register</a>
          to comment on this event.
        </p>
      <% else %>
        <%= form_tag event_comments_path event, method: :post do %>
          <div class="form-group">
            <label for="comment">Your comment</label>
            <textarea class="form-control" id="comment" name="comment" placeholder="Comment on this event, please be respectful :-)" rows="5"></textarea>
          </div>

          <input type="submit" class="btn btn-default" value="Submit">
        <% end %>
      <% end %>

      <% event.displayable_comments.each do |comment| %>
        <hr />

        <%= simple_format comment.text %>

        <p class="text-italic">
          <%= user_avatar comment.creator %>
          <%= user_github_link comment.creator %>

          <span class="pull-right">
            <%= local_time comment.created_at %>
          </span>
        </p>
      <% end %>
    </div>
  </div>
</div>