config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }

  devise_scope :user do
    delete "/users/sign_out" => "devise/sessions#destroy"
  end

  root "events#index"

  resources :conferences, only: [:index, :edit, :update]

  resources :events do
    member do
      post :list
    end

    resources :comments, only: [:create]
  end

  resources :users, only: [:index] do
    collection do
      get :me
      put :me, action: :update_me
    end

    member do
      post "promote/:role", action: :promote, as: :promote
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :omniauthable, :rememberable, :trackable
  include IsUser

  before_save :adjust_twitter_handle

  def adjust_twitter_handle
    self.twitter_handle = "@#{self.twitter_handle}" if self.twitter_handle.present? && self.twitter_handle[0] != '@'
  end

  class << self
    def for_admin
      order(:name, :username, :email)
    end

    def from_auth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.name = auth.info.name
        user.username = auth.info.nickname
        user.email = auth.info.email
        user.avatar = auth.info.image
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :verify_access, except: [:me, :update_me]

  def index
  end

  def me
  end

  def promote
    active_user.promote_user! params
    flash[:error] = "You promoted a user!"
    redirect_to users_path
  end

  def update_me
    active_user.update_me! params
    flash[:info] = "Your user information has been updated."
    redirect_to me_users_path
  end

  private

  def verify_access
    raise PermissionError unless active_user.can_manipulate_users?
  end
end

app/views/users/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>GitHub</th>
      <th>Email</th>
      <th>Role</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% User.for_admin.each do |user| %>
      <tr>
        <td><%= user_avatar user %></td>
        <td><%= user.name %></td>
        <td><%= user_github_link user, label: user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>

        <td>
          <% unless user.admin? %>
            <%= link_to "promote to admin", promote_user_path(user, "admin"), method: :post, class: "btn btn-danger", data: { confirm: "Are you sure you want to promote them?" } %>
          <% end %>

          <% unless user.super_admin? %>
            <%= link_to "promote to super_admin", promote_user_path(user, "super_admin"), method: :post, class: "btn btn-danger", data: { confirm: "Are you sure you want to promote them?" } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/me.html.erb
<%= form_tag me_users_path, method: :put, data: { guarded: true } do %>
  <div class="row">
    <div class="col-xs-2">
      <%= user_avatar active_user, { class: "img-responsive" } %>
    </div>

    <div class="col-xs-10 col-sm-6">
      <div class="row">
        <div class="col-sm-12">
          <div class="form-group">
            <label for="name">Name</label> <small class="text-muted">(required)</small>
            <input type="text" class="form-control" id="name" name="name" placeholder="John Doe" data-guard="required" value="<%= active_user.display_name %>" />
          </div>
        </div>

        <div class="col-sm-12">
          <div class="form-group">
            <label for="email">Email</label>
            <input type="text" class="form-control" id="email" name="email" placeholder="john@example.com" data-guard="email" value="<%= active_user.email %>" />
          </div>
        </div>

        <div class="col-sm-12">
          <div class="form-group">
            <label for="github_username">GitHub Username</label>
            <input type="text" class="form-control" id="github_username" value="<%= active_user.username %>" disabled="true" />
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <% if active_user.really_admin? %>
      <div class="col-sm-8">
        <div class="checkbox">
          <label>
            <input type="checkbox" name="incognito" value="true" <%= "checked" if active_user.incognito_admin? %> />
            Incognito mode
          </label>
        </div>
      </div>
    <% end %>

    <div class="col-sm-8">
      <input type="submit" class="btn btn-default" value="Save">
    </div>
  </div>
<% end %>