config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }

  devise_scope :user do
    delete "/users/sign_out" => "devise/sessions#destroy"
  end

  root "events#index"

  resources :conferences, only: [:index, :edit, :update]

  resources :events do
    member do
      post :list
    end

    resources :comments, only: [:create]
  end

  resources :users, only: [:index] do
    collection do
      get :me
      put :me, action: :update_me
    end

    member do
      post "promote/:role", action: :promote, as: :promote
    end
  end
end

app/models/conference.rb
class Conference < ActiveRecord::Base
  belongs_to :creator, foreign_key: "creator_user_id", class_name: "User"
  has_many :events
  validate :dates_match_year
  validate :dates_in_proper_order

  def each_day(active_user)
    events = Event.for_user(active_user).to_a

    allow_starting_at.upto allow_ending_at do |date|
      day = Day.new self, events, date

      if day.empty?
        next unless day.conference_day?
      end

      yield day
    end
  end

  def iso_valid_end_date
    allow_ending_at.strftime "%Y-%m-%d"
  end

  def iso_valid_start_date
    allow_starting_at.strftime "%Y-%m-%d"
  end

  def parse_date_time(time_str)
    zone.parse DateTime.strptime(time_str, "%m/%d/%Y %I:%M %p").strftime("%Y-%m-%d %H:%M:%S")
  end

  def valid_end_date
    allow_ending_at.strftime "%-m/%-d"
  end

  def valid_start_date
    allow_starting_at.strftime "%-m/%-d"
  end

  def zone
    ActiveSupport::TimeZone[timezone]
  end

  def fill(params)
    self.year = params[:year]
    self.timezone = params[:timezone]
    self.starting_at = Date.strptime(params[:start_date], "%m/%d/%Y")
    self.ending_at = Date.strptime(params[:end_date], "%m/%d/%Y")
    self.allow_starting_at = Date.strptime(params[:allow_start_date], "%m/%d/%Y")
    self.allow_ending_at = Date.strptime(params[:allow_end_date], "%m/%d/%Y")
    self.header = params[:header]
  end

  private

  def dates_match_year
    [:allow_starting_at, :starting_at, :ending_at, :allow_ending_at].each do |field|
      if send(field).year != year
        errors.add(field, "must be in the year of the conference")
      end
    end
  end

  FIELD_LABELS = {
    allow_starting_at: "allowed start date",
    starting_at: "conference start date",
    ending_at: "conference end date",
    allow_ending_at: "allowed end date",
  }

  def dates_in_proper_order
    {
      allow_starting_at: [:starting_at, :ending_at, :allow_ending_at],
      starting_at: [:ending_at, :allow_ending_at],
      ending_at: [:allow_ending_at]
    }.each do |check_field, fields|
      fields.each do |field|
        if send(field) < send(check_field)
          errors.add(field, "must be greater or equal to the #{FIELD_LABELS[check_field]}")
        end
      end
    end

    {
      allow_ending_at: [:allow_starting_at, :starting_at, :ending_at],
      ending_at: [:allow_starting_at, :starting_at],
      starting_at: [:allow_starting_at]
    }.each do |check_field, fields|
      fields.each do |field|
        if send(field) > send(check_field)
          errors.add(field, "must be less than or equal to the #{FIELD_LABELS[check_field]}")
        end
      end
    end
  end

  class << self
    def for_admin
      order(:year, :starting_at)
    end

    def current
      where(year: Time.now.year).first
    end
  end
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  before_filter :verify_access

  def index
  end

  def edit
    @conference = Conference.find params[:id]
  end

  def update
    active_user.edit_conference! params
    flash[:info] = "The conference has been updated."
    redirect_to conferences_path
  end

  private

  def verify_access
    raise PermissionError unless active_user.can_manipulate_conferences?
  end
end

app/views/conferences/edit.html.erb
<%= form_tag conference_path(@conference), method: :put, data: { guarded: true } do %>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <label for="year">Year</label> <small class="text-muted">(required)</small>
        <input type="text" class="form-control" id="year" name="year" placeholder="Ex: <%= Date.today.year %>" data-guard="required int" value="<%= @conference.year %>" data-guard-int-min="2000" data-guard-int-max="3000" data-guard-int-message="Please enter a reasonable year." />
      </div>

      <div class="form-group">
        <label for="timezone">Time Zone</label> <small class="text-muted">(required)</small>
        <select class="form-control" id="timezone" name="timezone">
          <% ActiveSupport::TimeZone.all.sort_by(&:to_s).each do |zone| %>
            <option value="<%= zone.name %>" <%= "selected" if @conference.zone == zone %>><%= zone.to_s %></option>
          <% end %>
        </select>
      </div>

      <fieldset class="well">
        <legend>Conference Dates</legend>

        <div class="row">
          <div class="col-sm-6">
            <div class="form-group">
              <label for="start_date">Start Date</label> <small class="text-muted">(required)</small>
              <input type="text" class="form-control" id="start_date" name="start_date" placeholder="Ex: <%= format_date Date.today %>" data-guard="required dateUS conferencedate" value="<%= format_date @conference.starting_at %>" data-conferencedate-year="input[name='year']" data-conferencedate-greater-than="input[name='allow_start_date']" data-conferencedate-less-than="input[name='end_date'],input[name='allow_end_date']" data-conferencedate-label="conference start date" />
            </div>
          </div>

          <div class="col-sm-6">
            <div class="form-group">
              <label for="end_date">End Date</label> <small class="text-muted">(required)</small>
              <input type="text" class="form-control" id="end_date" name="end_date" placeholder="Ex: <%= format_date Date.today %>" data-guard="required dateUS conferencedate" value="<%= format_date @conference.ending_at %>" data-conferencedate-year="input[name='year']" data-conferencedate-greater-than="input[name='start_date'],input[name='allow_start_date']" data-conferencedate-less-than="input[name='allow_end_date']" data-conferencedate-label="conference end date" />
            </div>
          </div>
        </div>
      </fieldset>

      <fieldset class="well">
        <legend>Allowed Event Dates</legend>

        <div class="row">
          <div class="col-sm-6">
            <div class="form-group">
              <label for="allow_start_date">Allowed Start Date</label> <small class="text-muted">(required)</small>
              <input type="text" class="form-control" id="allow_start_date" name="allow_start_date" placeholder="Ex: <%= format_date Date.today %>" data-guard="required dateUS conferencedate" value="<%= format_date @conference.allow_starting_at %>" data-conferencedate-year="input[name='year']" data-conferencedate-less-than="input[name='start_date'],input[name='end_date'],input[name='allow_end_date']" data-conferencedate-label="allowed start date" />
            </div>
          </div>

          <div class="col-sm-6">
            <div class="form-group">
              <label for="allow_end_date">Allowed End Date</label> <small class="text-muted">(required)</small>
              <input type="text" class="form-control" id="allow_end_date" name="allow_end_date" placeholder="Ex: <%= format_date Date.today %>" data-guard="required dateUS conferencedate" value="<%= format_date @conference.allow_ending_at %>" data-conferencedate-year="input[name='year']" data-conferencedate-greater-than="input[name='start_date'],input[name='end_date'],input[name='allow_start_date']" data-conferencedate-label="allowed end date" />
            </div>
          </div>
        </div>
      </fieldset>

      <fieldset class="well">
        <legend>Header</legend>

        <div class="form-group">
          <textarea class="form-control" id="header" name="header" placeholder="Header HTML" rows="5"><%= @conference.header %></textarea>
        </div>

        <button id="header-preview" class="btn btn-default">Preview</button>
        <hr />

        <div id="header-preview-content">
        </div>
      </fieldset>

      <input type="submit" class="btn btn-default" value="Update" />
    </div>
  </div>
<% end %>

app/views/conferences/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Time Zone</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% Conference.for_admin.each do |conference| %>
      <tr class="<%= "text-bold" if conference == current_conference %>">
        <td><%= format_date conference.starting_at %></td>
        <td><%= format_date conference.ending_at %></td>
        <td><%= conference.timezone %></td>

        <td>
          <a class="btn btn-default btn-xs" href="<%= edit_conference_path(conference) %>">
            <span class="glyphicon glyphicon-pencil"></span>
          </a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>