config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }

  devise_scope :user do
    delete "/users/sign_out" => "devise/sessions#destroy"
  end

  root "events#index"

  resources :conferences, only: [:index, :edit, :update]

  resources :events do
    member do
      post :list
    end

    resources :comments, only: [:create]
  end

  resources :users, only: [:index] do
    collection do
      get :me
      put :me, action: :update_me
    end

    member do
      post "promote/:role", action: :promote, as: :promote
    end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :conference
  belongs_to :creator, foreign_key: "creator_user_id", class_name: "User"
  belongs_to :deleted_by, foreign_key: "deleted_by_user_id", class_name: "User"
  has_many :coordinators
  has_many :comments
  validates :name, presence: true
  validate :date_within_conference_allowed_dates

  def coordinator?(user)
    return false unless user
    coordinators.map(&:user).include?(user)
  end

  def current?
    time_state == :current
  end

  def display_classes(active_user)
    classes = []

    unless listed?
      if active_user.admin?
        classes << "unlisted"
      else
        classes << "pending"
      end
    end

    case time_state
    when :past
      classes << "past"
    when :current
      classes << "current"
    when :future
      classes << "future"
    end

    classes.join " "
  end

  def display_id
    "event-#{id}"
  end

  def displayable_comments
    comments.for_display
  end

  def ending_at
    fix_tz read_attribute(:ending_at)
  end

  def fill(params)
    self.name = params[:name]
    fill_coordinators(params)
    self.url = params[:url]
    self.location = params[:location]
    self.description = params[:description]
    self.starting_at = conference.parse_date_time "#{params[:date]} #{params[:start_time]}"
    self.ending_at = conference.parse_date_time  "#{params[:date]} #{params[:end_time]}"

    if ending_at < starting_at
      self.ending_at += 1.day
    end
  end

  def fill_coordinators(params)
    raise "Invalid coordinators!" unless params[:coordinators].to_a.size == params[:coordinator_twitters].to_a.size
    raise "Invalid coordinators!" if params[:coordinator_githubs].present? && params[:coordinators].to_a.size != params[:coordinator_githubs].to_a.size
    coordinators.destroy_all
    return if params[:coordinators].blank? && params[:coordinator_twitters].blank? && params[:coordinator_githubs].blank?

    params[:coordinators].to_a.each_with_index do |name, i|
      twitter = params[:coordinator_twitters][i]
      github = params[:coordinator_githubs][i] if params[:coordinator_githubs].present?
      next if name.blank? && twitter.blank? && github.blank?
      user = User.find_by_username(github) if github.present?

      if user
        next if coordinators.any? { |x| x.user == user }
        coordinators.build name: name, twitter: twitter, user: user
      else
        next if coordinators.any? { |x| x.matches?(name, twitter, github) }
        coordinators.build name: name, twitter: twitter, username: github
      end
    end
  end

  def future?
    time_state == :future
  end

  def past?
    time_state == :past
  end

  def starting_at
    fix_tz read_attribute(:starting_at)
  end

  def time_state
    now = conference.zone.now

    if ending_at < now
      :past
    elsif starting_at <= now && ending_at >= now
      :current
    elsif starting_at > now
      :future
    end
  end

  def signups_enabled?
    # TODO
    false
  end

  private

  def date_within_conference_allowed_dates
    if starting_at.to_date < conference.allow_starting_at
      errors.add(:starting_at, "can't be before conference allowed start")
    end

    if starting_at.to_date > conference.allow_ending_at
      errors.add(:starting_at, "can't be after conference allowed end")
    end
  end

  def fix_tz(time)
    if time
      time.in_time_zone conference.timezone
    end
  end

  class << self
    def display_order
      order :starting_at, :ending_at, :name
    end

    def for_user(active_user)
      if active_user.admin?
        includes(:creator).not_deleted.display_order
      else
        includes(:creator).listed_or_by(active_user).not_deleted.display_order
      end
    end

    def listed
      where listed: true
    end

    def listed_or_by(user)
      if user.anonymous?
        listed
      else
        where "(listed = ? OR creator_user_id = ?)", true, user.id
      end
    end

    def not_deleted
      where deleted: false
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def create
    active_user.create_event! params, request.remote_ip
    flash[:info] = "Thanks for submitting your event!"
    redirect_to events_path
  end

  def destroy
    active_user.destroy_event! params
    flash[:error] = "Event deleted!"
    redirect_to events_path
  end

  def edit
    @event = Event.find params[:id]
    raise PermissionError unless active_user.can_edit? @event
  end

  def index
  end

  def list
    active_user.list_event! params
    flash[:error] = "Event listed!"
    redirect_to events_path
  end

  def new
  end

  def show
    @event = Event.find params[:id]
  end

  def update
    active_user.edit_event! params
    flash[:info] = "Thanks for editing your event!"
    redirect_to events_path
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def coordinator_col_class
    if active_user.can_specify_user_coordinators?
      "col-sm-4"
    else
      "col-sm-6"
    end
  end
end

app/views/events/_editing_buttons.html.erb
<% if active_user.can_edit? event %>
  <%= "<p>".html_safe if local_assigns[:wrap] %>
    <a class="btn btn-default" href="<%= edit_event_path event %>">edit</a>

    <% if !event.listed? && active_user.can_list?(event) %>
      <%= link_to "list", list_event_path(event), method: :post, class: "btn btn-danger", data: { confirm: "Are you sure you want to list that?" } %>
    <% end %>

    <% if active_user.can_delete? event %>
      <%= link_to "delete", event_path(event), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure you want to delete that?" } %>
    <% end %>
  <%= "</p>".html_safe if local_assigns[:wrap] %>
<% end %>

app/views/events/_event.html.erb
<p>
  <strong>Time:</strong>
  <%= format_time event.starting_at %> - <%= format_time event.ending_at %>
</p>

<% if event.url.present? %>
  <p>
    <% if event.listed? %>
      <a href="<%= event.url %>"><%= event.url %></a>
    <% else %>
      <strong>URL:</strong>
      <%= event.url %>
    <% end %>
  </p>
<% end %>

<% unless event.coordinators.empty? %>
  <p>
    <strong><%= "Coordinator".pluralize(event.coordinators.size) %>:</strong>
    <% event.coordinators.each_with_index do |coordinator, i| %>
      <% comma = "," if i < event.coordinators.size - 1 %>

      <% if coordinator.user %>
        <%= user_avatar coordinator.user %>
        <%= user_github_link coordinator.user %><%= comma %>
      <% elsif coordinator.name.present? && coordinator.twitter.present? %>
        <%= link_to coordinator.name, coordinator.twitter_path %><%= comma %>
      <% elsif coordinator.twitter.present? %>
        <%= link_to coordinator.twitter, coordinator.twitter_path %><%= comma %>
      <% elsif coordinator.name.present? && coordinator.username.present? %>
        <%= link_to coordinator.name, coordinator.github_path %><%= comma %>
      <% elsif coordinator.username.present? %>
        <%= link_to coordinator.username, coordinator.github_path %><%= comma %>
      <% else %>
        <%= coordinator.name %><%= comma %>
      <% end %>
    <% end %>
  </p>
<% end %>

<% if event.location.present? %>
  <p>
    <strong>Location:</strong>
    <%= event.location %>
  </p>
<% end %>

<% if event.description.present? %>
  <div class="text-italic">
    <%= simple_format event.description %>
  </div>
<% end %>

<% if event.creator.present? %>
  <p class="text-italic">
    submitted by
    <%= user_avatar event.creator %>
    <%= user_github_link event.creator %>
  </p>
<% elsif active_user.admin? && event.anonymous_user_ip.present? %>
  <p>
    <em>
      submitted by <%= event.anonymous_user_ip %>
    </em>
  </p>
<% end %>

app/views/events/_events.html.erb
<h2 class="day-label <%= day.display_classes %>">
  <a class="day-expander" data-toggle="collapse" href="#<%= day.display_id %>" aria-expanded="<%= !day.entirely_past? %>" aria-controls="<%= day.display_id %>">
    <%= day.label %>
  </a>
</h2>

<div id="<%= day.display_id %>" class="day-content collapse <%= "in" unless day.entirely_past? %>">
  <% if day.events.empty? %>
    <em class="lead">None yet...</em>
  <% else %>
    <% day.events.each do |event| %>
      <div class="well event-well <%= event.display_classes active_user %>">
        <div class="title">
          <% unless event.listed? %>
            <span class="label label-primary" data-toggle="tooltip" data-placement="top" title="This event is pending spam check before it is visible to everyone">unlisted</span>
          <% end %>

          <a class="event-expander" data-toggle="collapse" href="#<%= event.display_id %>" aria-expanded="<%= !event.past? %>" aria-controls="<%= event.display_id %>">
            <%= event.name %>
          </a>
        </div>

        <div id="<%= event.display_id %>" class="collapse <%= "in" unless event.past? %>">
          <%= render event %>

          <p>
            <a class="btn btn-link comments-link" href="<%= event_path event %>">
              comments
              <% if event.comments.size > 0 %>
                (<%= event.comments.size %>)
              <% end %>
            </a>

            <%= partial "events/editing_buttons", event: event %>
          </p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/events/_form.html.erb
<div class="row">
  <div class="col-sm-10">
    <%= partial "shared/panel", id: "basics", expanded: true, title: "The Basics (required)" do %>
      <div class="form-group">
        <label for="name">Name</label>
        <input type="text" class="form-control" id="name" name="name" placeholder="Event name" data-guard="required" value="<%= event.name %>" />
      </div>

      <div class="row">
        <div class="col-sm-4">
          <div class="form-group">
            <label for="date">Date</label>
            <input type="text" class="form-control" id="date" name="date" placeholder="Ex: <%= format_date(current_conference.starting_at + 1.day) %>" data-guard="required dateUS confDates" data-guard-conf-dates-message="Valid dates: <%= current_conference.valid_start_date %> - <%= current_conference.valid_end_date %>." data-valid-starting-at="<%= current_conference.iso_valid_start_date %>" data-valid-ending-at="<%= current_conference.iso_valid_end_date %>" value="<%= format_date event.starting_at %>" />
          </div>
        </div>

        <div class="col-sm-4">
          <div class="form-group">
            <label for="start_time">Start Time</label>
            <input type="text" class="form-control" id="start_time" name="start_time" placeholder="Ex: 7:00 pm" data-guard="required timeUS" value="<%= format_time event.starting_at %>" />
          </div>
        </div>

        <div class="col-sm-4">
          <div class="form-group">
            <label for="end_time">End Time</label>
            <input type="text" class="form-control" id="end_time" name="end_time" placeholder="Ex: 7:30 pm" data-guard="required timeUS" value="<%= format_time event.ending_at %>" />
          </div>
        </div>
      </div>
    <% end %>

    <%= partial "shared/panel", id: "coordinators", expanded: true, title: "Coordinators" do %>
      <% event.coordinators.each_with_index do |coordinator, i| %>
        <%= render coordinator, index: i %>
      <% end %>

      <%= render Coordinator.new, index: event.coordinators.size %>

      <script type="text/x-tmpl" id="new-coordinator-template">
        <%= render Coordinator.new, index: "{%= o.rowSize %}" %>
      </script>
    <% end %>

    <%= partial "shared/panel", id: "details", expanded: true, title: "Details" do %>
      <div class="form-group">
        <label for="url">URL</label>
        <input type="text" class="form-control" id="url" name="url" placeholder="Event URL" value="<%= event.url %>" />
      </div>

      <div class="form-group">
        <label for="location">Location</label>
        <input type="text" class="form-control" id="location" name="location" placeholder="Event location" value="<%= event.location %>" />
      </div>

      <div class="form-group">
        <label for="description">Description</label>
        <textarea class="form-control" id="description" name="description" placeholder="Event description" rows="5"><%= event.description %></textarea>
      </div>
    <% end %>

    <% if active_user.can_specify_signups? %>
      <%= partial "shared/panel", id: "signups", expanded: true, title: "Signups" do %>
        <p>
          <em>Signups will allow users to confirm that they want to go
          to this event. You can also provide some questions before the
          user confirms.</em>
        </p>

        <div class="checkbox">
          <label>
            <input type="checkbox" name="signups_enabled" value="true" <%= "checked" if event.signups_enabled? %> />
            Enable signups
          </label>
        </div>

        <div class="row">
          <div class="col-xs-12">
            <div id="signups-content" class="collapse <%= "in" if event.signups_enabled? %>">
              <h4>Questions</h4>

              <div id="signups-questions-container">
              </div>

              <hr />

              <button id="add-signups-question" class="btn btn-default">Add Question</button>

              <script type="text/x-tmpl" id="new-signups-question-template">
                <%= render SignupsQuestion.new, index: "{%= o.rowSize %}" %>
              </script>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>

    <input type="submit" class="btn btn-default" value="<%= submit_label %>" />
  </div>
</div>

app/views/events/edit.html.erb
<%= form_tag event_path(@event), method: :put, data: { guarded: true } do %>
  <%= partial "form", event: @event, submit_label: "Update" %>
<% end %>

app/views/events/index.html.erb
<div class="row">
  <div class="col-sm-2 col-sm-push-10 col-md-2 col-md-push-10">
    <a class="btn btn-default btn-block" href="/events/new">Add Event</a>
  </div>

  <div class="col-sm-10 col-sm-pull-2 col-md-8 col-md-pull-2">
    <%= current_conference.header.to_s.html_safe %>
  </div>
</div>

<div class="row">
  <div class="col-sm-10 col-md-8">
    <% current_conference.each_day active_user do |day| %>
      <%= partial "events", day: day %>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<% if active_user.anonymous? %>
  <div class="row">
    <div class="col-sm-10">
      <div class="alert alert-warning" role="alert">
        <strong>WARNING:</strong> You will not be able to edit this event unless you <a href="<%= user_signup_and_login_path %>">sign in</a> first.
        It will also be invisible until it is verified as not spam.
      </div>
    </div>
  </div>
<% end %>

<%= form_tag events_path, method: :post, data: { guarded: true } do %>
  <%= partial "form", event: Event.new, submit_label: "Create" %>
<% end %>

app/views/events/show.html.erb
<h2><%= @event.name %></h2>
<%= render @event %>
<%= partial "events/editing_buttons", event: @event, wrap: true %>
<%= partial "comments/collection", event: @event %>